function cellPickList()
	return {
{xcell=11,ycell=19,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=11,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=11,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=11,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=11,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=11,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=11,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=11,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=11,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=11,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=11,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=11,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=11,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=11,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=11,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=11,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=11,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=11,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=11,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=11,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=11,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=12,ycell=19,area ="East Riverside Recreation Area",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=12,ycell=20,area ="Tanglewood",nearRoad=1,nearCiv=1,civDist=0,poi="Tanglewood",wild=3},
{xcell=12,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=12,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=3},
{xcell=12,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=3},
{xcell=12,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=3},
{xcell=12,ycell=25,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=3},
{xcell=12,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=3},
{xcell=12,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=12,ycell=28,area ="Small Town",nearRoad=1,nearCiv=1,civDist=0,poi="Small Town",wild=2},
{xcell=12,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=12,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=3},
{xcell=12,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=12,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=12,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=12,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=12,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=12,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=12,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=12,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=12,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=12,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=12,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=12,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=12,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=12,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=13,ycell=19,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=13,ycell=20,area ="Tanglewood",nearRoad=1,nearCiv=1,civDist=0,poi="Tanglewood",wild=3},
{xcell=13,ycell=21,area ="Tanglewood",nearRoad=1,nearCiv=1,civDist=0,poi="Tanglewood",wild=2},
{xcell=13,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=13,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=13,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=13,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=13,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=13,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=0,poi="Cabin",wild=4},
{xcell=13,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="Camp",wild=4},
{xcell=13,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=13,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=13,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=13,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=13,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=13,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=13,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=13,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=13,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=13,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=13,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=13,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=13,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=13,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=13,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=13,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=14,ycell=19,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=14,ycell=20,area ="Tanglewood",nearRoad=1,nearCiv=1,civDist=0,poi="Tanglewood",wild=3},
{xcell=14,ycell=21,area ="Tanglewood",nearRoad=1,nearCiv=1,civDist=0,poi="Tanglewood",wild=3},
{xcell=14,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=14,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=14,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="Camp",wild=4},
{xcell=14,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=14,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=14,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=14,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=14,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=14,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=14,ycell=31,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=14,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=14,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=14,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=14,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=14,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=14,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=14,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=14,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=14,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=14,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=14,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=18,poi="0",wild=4},
{xcell=14,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=18,poi="0",wild=4},
{xcell=14,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=23,poi="0",wild=4},
{xcell=15,ycell=19,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=15,ycell=20,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=15,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=15,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=15,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=15,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=15,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=15,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="Camp",wild=4},
{xcell=15,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="Camp",wild=4},
{xcell=15,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="Camp",wild=4},
{xcell=15,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=15,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=15,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=15,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=15,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=15,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=15,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=15,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=15,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=15,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=15,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=15,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=15,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=15,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=15,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=15,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=25,poi="0",wild=4},
{xcell=16,ycell=18,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=16,ycell=19,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=16,ycell=20,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Radio Tower",wild=4},
{xcell=16,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=16,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=3},
{xcell=16,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=16,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=16,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=16,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="Camp",wild=4},
{xcell=16,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=16,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=16,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=16,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=16,ycell=31,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=16,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=16,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=16,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=16,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=16,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=16,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=16,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=16,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=16,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=16,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=16,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=16,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=16,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=25,poi="0",wild=4},
{xcell=17,ycell=18,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=17,ycell=19,area ="East Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=17,ycell=20,area ="East Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=17,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=17,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=17,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=17,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=17,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=17,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=17,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=17,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=17,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=17,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=17,ycell=31,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=17,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=17,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=17,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=17,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=17,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=17,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=17,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=17,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=17,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=17,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=17,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=17,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=17,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=17,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=18,ycell=18,area ="East Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=18,ycell=19,area ="East Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=18,ycell=20,area ="East Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=18,ycell=21,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=0},
{xcell=18,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=18,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=18,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=18,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=18,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=18,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=18,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=18,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=18,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=18,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=18,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=18,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=18,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=18,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=18,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=18,ycell=41,area ="Military Base",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=4},
{xcell=18,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=18,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=18,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=19,ycell=17,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=19,ycell=18,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=2},
{xcell=19,ycell=19,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=2},
{xcell=19,ycell=20,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=19,ycell=21,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="Country Club",wild=3},
{xcell=19,ycell=22,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=19,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=19,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=19,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=19,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=19,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=19,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=19,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=19,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=19,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=19,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=19,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=19,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=19,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=19,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=19,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=19,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=19,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=19,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=19,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=19,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=19,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=19,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=17,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=20,ycell=18,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=20,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=20,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=20,ycell=21,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=20,ycell=22,area ="Country Club",nearRoad=1,nearCiv=1,civDist=0,poi="Country Club",wild=3},
{xcell=20,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=20,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=20,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=20,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=20,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=20,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=20,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=20,ycell=33,area ="Doe Valley",nearRoad=0,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=20,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=20,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=20,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=20,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=20,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=20,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=20,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=20,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=20,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=20,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=20,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=17,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=0},
{xcell=21,ycell=18,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=21,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=21,area ="Country Club",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=22,area ="Country Club",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=21,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=21,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=21,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=21,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=21,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=21,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=21,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=21,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=21,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=21,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=21,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=21,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=21,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=21,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=21,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=21,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=21,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=21,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=21,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=22,ycell=17,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=22,ycell=18,area ="Riverside",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=22,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=22,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=22,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=22,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=22,ycell=23,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=22,ycell=24,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=22,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=22,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=22,ycell=27,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=22,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=22,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=22,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=22,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=22,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=22,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=22,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=22,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=22,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=22,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=22,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=22,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=22,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=22,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=22,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=22,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=22,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=17,area ="West Riverside Farms",nearRoad=0,nearCiv=0,civDist=1,poi="Riverside",wild=2},
{xcell=23,ycell=18,area ="West Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=2},
{xcell=23,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=23,ycell=20,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=23,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=23,area ="Doe Valley",nearRoad=0,nearCiv=0,civDist=1,poi="Doe Valley",wild=3},
{xcell=23,ycell=24,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=23,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=23,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=23,ycell=27,area ="Fallas Lake",nearRoad=1,nearCiv=1,civDist=0,poi="Fallas Lake",wild=2},
{xcell=23,ycell=28,area ="Fallas Lake",nearRoad=1,nearCiv=1,civDist=0,poi="Fallas Lake",wild=3},
{xcell=23,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=23,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=23,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=23,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=23,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=23,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=23,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=23,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=23,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=23,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=23,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=23,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=23,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=24,ycell=17,area ="West Riverside Farms",nearRoad=0,nearCiv=0,civDist=1,poi="Riverside",wild=2},
{xcell=24,ycell=18,area ="West Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=1},
{xcell=24,ycell=19,area ="West Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=24,ycell=20,area ="West Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=24,ycell=21,area ="West Riverside Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Riverside",wild=3},
{xcell=24,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=24,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=24,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=24,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=24,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=24,ycell=27,area ="Fallas Lake",nearRoad=1,nearCiv=1,civDist=0,poi="Fallas Lake",wild=1},
{xcell=24,ycell=28,area ="Fallas Lake",nearRoad=1,nearCiv=1,civDist=0,poi="Fallas Lake",wild=1},
{xcell=24,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=24,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=24,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=24,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=24,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=24,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=24,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=24,ycell=36,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=24,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=24,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=24,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=24,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=24,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=0,civDist=1,poi="Rosewood",wild=2},
{xcell=24,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=24,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=24,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=25,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=25,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=25,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=25,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=3},
{xcell=25,ycell=27,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=3},
{xcell=25,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=25,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=25,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=25,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=25,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=25,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=25,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=25,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=25,ycell=36,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=25,ycell=37,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=25,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=25,ycell=39,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Prison",wild=1},
{xcell=25,ycell=40,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=25,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=25,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=25,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=25,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=26,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=26,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=26,ycell=25,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="Cabin",wild=4},
{xcell=26,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=26,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=26,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=26,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=26,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=26,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=26,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=26,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=26,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=26,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=26,ycell=36,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=26,ycell=37,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=26,ycell=38,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=26,ycell=39,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=2},
{xcell=26,ycell=40,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=26,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=2},
{xcell=26,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=26,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=26,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=27,ycell=25,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=27,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=27,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="Camp",wild=4},
{xcell=27,ycell=28,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=27,ycell=29,area ="Doe Valley",nearRoad=0,nearCiv=0,civDist=3,poi="Doe Valley",wild=3},
{xcell=27,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=2,poi="Doe Valley",wild=1},
{xcell=27,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=27,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=27,ycell=33,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=27,ycell=34,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=27,ycell=35,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=27,ycell=36,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=27,ycell=37,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=27,ycell=38,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=27,ycell=39,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=27,ycell=40,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=27,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=27,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=27,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=27,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=28,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=28,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Cabin",wild=4},
{xcell=28,ycell=27,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=28,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=28,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=28,ycell=30,area ="Doe Valley",nearRoad=0,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=28,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=28,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=2},
{xcell=28,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=28,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=28,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=28,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=28,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=28,ycell=38,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=28,ycell=39,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=28,ycell=40,area ="Rosewood",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=3},
{xcell=28,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=28,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=28,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=28,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=29,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=29,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=2,poi="Doe Valley",wild=0},
{xcell=29,ycell=27,area ="Doe Valley",nearRoad=0,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=29,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=29,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=29,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=29,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=29,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=29,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=29,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=29,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=29,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=29,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=29,ycell=38,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=29,ycell=39,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=0},
{xcell=29,ycell=40,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=29,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=29,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=29,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=29,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=30,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=30,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=30,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=30,ycell=27,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=30,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=0},
{xcell=30,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=30,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=0},
{xcell=30,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=1},
{xcell=30,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=30,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=30,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=30,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=30,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=30,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=30,ycell=38,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=30,ycell=39,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=0},
{xcell=30,ycell=40,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=0},
{xcell=30,ycell=41,area ="Rosewood Farms",nearRoad=1,nearCiv=1,civDist=0,poi="Rosewood",wild=1},
{xcell=30,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=30,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=30,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=31,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=31,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=31,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=31,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=1},
{xcell=31,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=1},
{xcell=31,ycell=27,area ="Doe Valley",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=3},
{xcell=31,ycell=28,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=31,ycell=29,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=31,ycell=30,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=31,ycell=31,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=31,ycell=32,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=31,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=31,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="Cabin",wild=4},
{xcell=31,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=31,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=31,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=31,ycell=38,area ="Rosewood Farms",nearRoad=0,nearCiv=0,civDist=1,poi="Rosewood",wild=3},
{xcell=31,ycell=39,area ="Rosewood Farms",nearRoad=1,nearCiv=0,civDist=1,poi="Rosewood",wild=3},
{xcell=31,ycell=40,area ="Rosewood Farms",nearRoad=0,nearCiv=0,civDist=1,poi="Rosewood",wild=3},
{xcell=31,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=31,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=31,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=31,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=32,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=32,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=32,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=1},
{xcell=32,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=1},
{xcell=32,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="Cabin",wild=4},
{xcell=32,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=32,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=32,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=32,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=32,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=32,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=32,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=32,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=32,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=32,ycell=42,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="March Ridge",wild=3},
{xcell=32,ycell=43,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="March Ridge",wild=3},
{xcell=32,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=22,area ="Westpoint Remote",nearRoad=1,nearCiv=0,civDist=2,poi="Westpoint",wild=3},
{xcell=33,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=24,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=33,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=1,poi="Doe Valley",wild=1},
{xcell=33,ycell=26,area ="Doe Valley",nearRoad=1,nearCiv=0,civDist=2,poi="Doe Valley",wild=3},
{xcell=33,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=33,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=33,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=33,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=31,area ="McCoy",nearRoad=1,nearCiv=1,civDist=0,poi="McCoy",wild=3},
{xcell=33,ycell=32,area ="McCoy",nearRoad=1,nearCiv=1,civDist=0,poi="McCoy",wild=3},
{xcell=33,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=33,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=36,area ="Muldraugh Industrial Zone",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=1},
{xcell=33,ycell=37,area ="Muldraugh Industrial Zone",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=3},
{xcell=33,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=33,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=33,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=33,ycell=42,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="March Ridge",wild=0},
{xcell=33,ycell=43,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="March Ridge",wild=0},
{xcell=33,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=24,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=1},
{xcell=34,ycell=25,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=1},
{xcell=34,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Radio Tower",wild=4},
{xcell=34,ycell=30,area ="McCoy",nearRoad=1,nearCiv=1,civDist=0,poi="McCoy",wild=3},
{xcell=34,ycell=31,area ="McCoy",nearRoad=1,nearCiv=1,civDist=0,poi="McCoy",wild=3},
{xcell=34,ycell=32,area ="McCoy",nearRoad=1,nearCiv=1,civDist=0,poi="McCoy",wild=3},
{xcell=34,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=36,area ="Muldraugh Industrial Zone",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=3},
{xcell=34,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=34,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=41,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=3},
{xcell=34,ycell=42,area ="March Ridge",nearRoad=1,nearCiv=1,civDist=0,poi="March Ridge",wild=0},
{xcell=34,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=34,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=35,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=23,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=3},
{xcell=35,ycell=24,area ="Doe Valley",nearRoad=1,nearCiv=1,civDist=0,poi="Doe Valley",wild=2},
{xcell=35,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=35,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=35,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=35,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=30,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=3},
{xcell=35,ycell=31,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=0},
{xcell=35,ycell=32,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=0},
{xcell=35,ycell=33,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=0},
{xcell=35,ycell=34,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=0},
{xcell=35,ycell=35,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=3},
{xcell=35,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=35,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=35,ycell=39,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=35,ycell=40,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=35,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=42,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=35,ycell=43,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=35,ycell=44,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=36,ycell=22,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=2},
{xcell=36,ycell=23,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=3},
{xcell=36,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=36,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=36,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=36,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=36,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=36,ycell=29,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=4},
{xcell=36,ycell=30,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=4},
{xcell=36,ycell=31,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=2},
{xcell=36,ycell=32,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=2},
{xcell=36,ycell=33,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=2},
{xcell=36,ycell=34,area ="Muldraugh",nearRoad=1,nearCiv=1,civDist=0,poi="Muldraugh",wild=3},
{xcell=36,ycell=35,area ="Muldraugh",nearRoad=0,nearCiv=0,civDist=1,poi="Cabin",wild=4},
{xcell=36,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=36,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=36,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=36,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=36,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=36,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=36,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=36,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=36,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=37,ycell=22,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=37,ycell=23,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=2},
{xcell=37,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=37,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=37,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=37,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Cabin",wild=4},
{xcell=37,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=31,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=37,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=37,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=37,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=37,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=37,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=37,ycell=39,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=37,ycell=40,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=37,ycell=41,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=37,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=37,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=37,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=21,poi="0",wild=4},
{xcell=38,ycell=22,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=38,ycell=23,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=38,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=38,ycell=25,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=38,ycell=26,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=38,ycell=27,area ="Crossroads",nearRoad=1,nearCiv=1,civDist=0,poi="Crossroads",wild=3},
{xcell=38,ycell=28,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=38,ycell=29,area ="Dixie",nearRoad=1,nearCiv=1,civDist=0,poi="Dixie",wild=3},
{xcell=38,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Cabin",wild=4},
{xcell=38,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=38,ycell=32,area ="Railyard",nearRoad=1,nearCiv=1,civDist=0,poi="Railyard",wild=1},
{xcell=38,ycell=33,area ="Railyard",nearRoad=1,nearCiv=1,civDist=0,poi="Railyard",wild=1},
{xcell=38,ycell=34,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=38,ycell=35,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=38,ycell=36,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=38,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=38,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=38,ycell=39,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=38,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=38,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=38,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=38,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=38,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=39,ycell=22,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=39,ycell=23,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=39,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="Camp",wild=4},
{xcell=39,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=39,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=39,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=39,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=39,ycell=29,area ="Dixie",nearRoad=1,nearCiv=1,civDist=0,poi="Dixie",wild=1},
{xcell=39,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=39,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=39,ycell=32,area ="Railyard",nearRoad=1,nearCiv=1,civDist=0,poi="Railyard",wild=3},
{xcell=39,ycell=33,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=39,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=39,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=39,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=39,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=39,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=39,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=39,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=39,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=39,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=39,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=39,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=40,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=40,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=40,ycell=22,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=40,ycell=23,area ="Westpoint",nearRoad=1,nearCiv=1,civDist=0,poi="Westpoint",wild=1},
{xcell=40,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="Camp",wild=4},
{xcell=40,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=40,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=40,ycell=27,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=40,ycell=28,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=40,ycell=29,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=40,ycell=30,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=40,ycell=31,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=40,ycell=32,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=40,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=40,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=40,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=40,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=40,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=40,ycell=38,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=40,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=40,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=40,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=40,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=40,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=40,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=21,poi="0",wild=4},
{xcell=41,ycell=3,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=0},
{xcell=41,ycell=14,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=0},
{xcell=41,ycell=15,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=41,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=41,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=41,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=41,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=41,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=41,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=41,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=41,ycell=24,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=41,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=41,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=41,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=41,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=41,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="Camp",wild=4},
{xcell=41,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="Camp",wild=4},
{xcell=41,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=41,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=41,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=41,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=41,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=41,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=41,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=41,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=41,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=41,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=41,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=41,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=41,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=41,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=25,poi="0",wild=4},
{xcell=42,ycell=3,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=42,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=42,ycell=14,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=42,ycell=15,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=42,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=42,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=42,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=42,ycell=19,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=42,ycell=20,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=42,ycell=21,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Cabin",wild=3},
{xcell=42,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=42,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=42,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=42,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=42,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=42,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=42,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=42,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=42,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=42,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=42,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=42,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=42,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=42,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=42,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=42,ycell=37,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=42,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=42,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=42,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=42,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=42,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=42,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=42,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=23,poi="0",wild=4},
{xcell=43,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=43,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=43,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=43,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=43,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=43,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=43,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=43,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=43,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=43,ycell=13,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=43,ycell=14,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=43,ycell=15,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=43,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=43,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=43,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=43,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=43,ycell=20,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=43,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=43,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=43,ycell=23,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=43,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=43,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=43,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=43,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=43,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=43,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=43,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=43,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=43,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=43,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=43,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=43,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=43,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=43,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=43,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=43,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=43,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=43,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=43,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=43,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=43,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=26,poi="0",wild=4},
{xcell=44,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=44,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=44,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=44,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=44,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=44,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=44,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=44,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=44,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=44,ycell=13,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=44,ycell=14,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=44,ycell=15,area ="Valley Station",nearRoad=0,nearCiv=0,civDist=1,poi="Valley Station",wild=1},
{xcell=44,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=1},
{xcell=44,ycell=17,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=44,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=44,ycell=19,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=44,ycell=20,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=44,ycell=21,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=44,ycell=22,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=44,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=44,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=44,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=44,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=44,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=44,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=44,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=44,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=44,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=44,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=44,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=44,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=44,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=44,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=44,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=44,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=44,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=44,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=44,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=44,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=44,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=44,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=26,poi="0",wild=4},
{xcell=45,ycell=4,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=45,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=45,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=45,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=45,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=45,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=45,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=45,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=45,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=45,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=45,ycell=14,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=45,ycell=15,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=1},
{xcell=45,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=1},
{xcell=45,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=1},
{xcell=45,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=45,ycell=19,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=0},
{xcell=45,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=45,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=45,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="Camp",wild=4},
{xcell=45,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=45,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="Cabin",wild=4},
{xcell=45,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=45,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=45,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=45,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=45,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=45,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=45,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=45,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=45,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=45,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=45,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=45,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=45,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=45,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=45,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=45,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=45,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=45,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=45,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=45,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=25,poi="0",wild=4},
{xcell=46,ycell=4,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=46,ycell=5,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=46,ycell=6,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=46,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=46,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=46,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=0},
{xcell=46,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=46,ycell=11,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=46,ycell=12,area ="Louisville",nearRoad=1,nearCiv=0,civDist=1,poi="Louisville",wild=1},
{xcell=46,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=46,ycell=14,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=46,ycell=15,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=46,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=46,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=46,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=46,ycell=19,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=0},
{xcell=46,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=46,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=46,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="Camp",wild=4},
{xcell=46,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=46,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=46,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=46,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=46,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=46,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=46,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=46,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=46,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=46,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=46,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=46,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=46,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=46,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=46,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=46,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=46,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=46,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=46,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=46,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=46,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=46,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=25,poi="0",wild=4},
{xcell=47,ycell=4,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=47,ycell=5,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=47,ycell=6,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=47,ycell=7,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=47,ycell=8,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=47,ycell=9,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=47,ycell=10,area ="Louisville",nearRoad=0,nearCiv=0,civDist=1,poi="Louisville",wild=0},
{xcell=47,ycell=11,area ="Louisville",nearRoad=1,nearCiv=0,civDist=1,poi="Louisville",wild=0},
{xcell=47,ycell=12,area ="Louisville",nearRoad=0,nearCiv=0,civDist=1,poi="Louisville",wild=0},
{xcell=47,ycell=13,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=47,ycell=14,area ="Valley Station",nearRoad=1,nearCiv=0,civDist=1,poi="Valley Station",wild=2},
{xcell=47,ycell=15,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=47,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=0,civDist=1,poi="Valley Station",wild=2},
{xcell=47,ycell=17,area ="Valley Station",nearRoad=1,nearCiv=0,civDist=1,poi="Valley Station",wild=2},
{xcell=47,ycell=18,area ="Valley Station",nearRoad=1,nearCiv=0,civDist=1,poi="Valley Station",wild=2},
{xcell=47,ycell=19,area ="Valley Station",nearRoad=1,nearCiv=0,civDist=1,poi="Valley Station",wild=2},
{xcell=47,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=47,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=47,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=47,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=47,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=47,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=47,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=47,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=47,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=47,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=47,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=47,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=47,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=47,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=47,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=47,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=47,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=47,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=47,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=47,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=47,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=17,poi="0",wild=4},
{xcell=47,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=47,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=47,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=47,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=29,poi="0",wild=4},
{xcell=48,ycell=4,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=48,ycell=5,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=48,ycell=6,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=48,ycell=7,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=48,ycell=8,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=48,ycell=9,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=48,ycell=10,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=48,ycell=11,area ="Louisville",nearRoad=1,nearCiv=0,civDist=2,poi="Louisville",wild=1},
{xcell=48,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=1},
{xcell=48,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="0",wild=2},
{xcell=48,ycell=14,area ="Valley Station",nearRoad=0,nearCiv=0,civDist=1,poi="Valley Station",wild=1},
{xcell=48,ycell=15,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=2},
{xcell=48,ycell=16,area ="Valley Station",nearRoad=1,nearCiv=1,civDist=0,poi="Valley Station",wild=3},
{xcell=48,ycell=17,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=48,ycell=18,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=48,ycell=19,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=48,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=4,poi="0",wild=4},
{xcell=48,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=5,poi="0",wild=4},
{xcell=48,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=48,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=7,poi="0",wild=4},
{xcell=48,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=48,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=48,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=48,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=48,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=48,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=48,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=48,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=48,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=48,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=48,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=48,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=48,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=48,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=48,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=18,poi="0",wild=4},
{xcell=48,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=18,poi="0",wild=4},
{xcell=48,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=18,poi="0",wild=4},
{xcell=48,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=48,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=48,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=48,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=28,poi="0",wild=4},
{xcell=49,ycell=4,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=5,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=6,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=7,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=8,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=9,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=10,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=11,area ="Wilderness",nearRoad=1,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=12,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=2},
{xcell=49,ycell=13,area ="Louisville",nearRoad=1,nearCiv=1,civDist=0,poi="Louisville",wild=3},
{xcell=49,ycell=14,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=15,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=16,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=17,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=1,poi="0",wild=4},
{xcell=49,ycell=18,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=49,ycell=19,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=2,poi="0",wild=4},
{xcell=49,ycell=20,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=3,poi="0",wild=4},
{xcell=49,ycell=21,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=6,poi="0",wild=4},
{xcell=49,ycell=22,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=8,poi="0",wild=4},
{xcell=49,ycell=23,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=9,poi="0",wild=4},
{xcell=49,ycell=24,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=49,ycell=25,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=49,ycell=26,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=49,ycell=27,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=49,ycell=28,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=49,ycell=29,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=49,ycell=30,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=49,ycell=31,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=12,poi="0",wild=4},
{xcell=49,ycell=32,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=10,poi="0",wild=4},
{xcell=49,ycell=33,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=11,poi="0",wild=4},
{xcell=49,ycell=34,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=13,poi="0",wild=4},
{xcell=49,ycell=35,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=14,poi="0",wild=4},
{xcell=49,ycell=36,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=49,ycell=37,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=49,ycell=38,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=19,poi="0",wild=4},
{xcell=49,ycell=39,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=19,poi="0",wild=4},
{xcell=49,ycell=40,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=19,poi="0",wild=4},
{xcell=49,ycell=41,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=49,ycell=42,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=15,poi="0",wild=4},
{xcell=49,ycell=43,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=16,poi="0",wild=4},
{xcell=49,ycell=44,area ="Wilderness",nearRoad=0,nearCiv=0,civDist=31,poi="0",wild=4},




}
end